import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { BackgroundCanvas } from "../components/background3d/BackgroundCanvas";
import { BackgroundEffectsProvider } from "../components/background3d/BackgroundEffectsProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  themeColor: "#050508",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Inline background prevents a white flash before CSS loads.
  const bg = "#050508";

  return (
    <html lang="en" style={{ backgroundColor: bg, colorScheme: "dark" }}>
      <body
        style={{ backgroundColor: bg }}
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-neutral-950 text-neutral-100`}
      >
        <BackgroundEffectsProvider>
          <BackgroundCanvas />
          <div className="relative z-10">{children}</div>
        </BackgroundEffectsProvider>
      </body>
    </html>
  );
}
